#!/usr/bin/env bash

# Install ufw
sudo apt-get install -y ufw

# Set default policies to deny all incoming traffic (as "filtered") and allow all outgoing traffic
sudo ufw default reject incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw --force enable

